#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Nov 25 16:06:01 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class ventana4(wx.Frame):
    def __init__(self, prent, informacion="", subtotal1=0, informacion2="", subtotal2=0):
        # begin wxGlade: ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(prent, style=wx.DEFAULT_FRAME_STYLE)
        self.SetSize((415, 301))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(51, 157, 209))

        #Variables de instancia de la ventana4
        self.infoTaquilla = informacion 
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal1
        self.subtotalDulceria = subtotal2
        self.total=self.subtotalTaquilla+self.subtotalDulceria

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./boletos1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./boletos1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTaquilla.SetBackgroundColour(wx.Colour(0, 236, 236))
        sizer_1.Add(lbTaquilla, 0, wx.EXPAND, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalTaquilla}")
        sizer_1.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbDulceria.SetBackgroundColour(wx.Colour(0, 243, 243))
        sizer_1.Add(lbDulceria, 0, wx.EXPAND, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalDulceria}")
        lbSubtotalDulceria.SetForegroundColour(wx.Colour(0, 0, 0))
        sizer_1.Add(lbSubtotalDulceria, 0, 0, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"Total: ${self.subtotalTaquilla+self.subtotalDulceria}")
        lbTotal.SetForegroundColour(wx.Colour(255, 39, 10))
        sizer_1.Add(lbTotal, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar\n")
        grid_sizer_3.Add(btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar\n")
        grid_sizer_3.Add(btnFinalizar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cerrara la ventana.\n"\
                                    "¿Esta seguro que desea cancelar su compra?","Confirmar cancelacion",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print("Bye!")
            self.Close()

        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        total = self.infoTaquilla+self.infoDulceria
        mensaje = (f"Confirmacion de Ticket\n\n"
                   f"¿Esta seguro que desea pagar?\n\n"
                   f"Total a pagar: ${total}\n"
                   f"Subtotal Ticket: ${self.subtotalTaquilla+self.subtotalDulceria}")
        respuesta = wx.MessageBox(
            mensaje,
            "Confirmacion",
            wx.YES_NO | wx.ICON_QUESTION
        )
        if respuesta == wx.YES:
            wx.MessageBox("Venta finalizada", "Exito", wx.OK | wx.ICON_INFORMATION)
            v2 = ventana2(self)
            v2.Show()
            self.Hide()
        else:
            self.Close()
            wx.GetApp().ExitMainLoop()
        event.Skip()

# end of class ventana4
class ventana3(wx.Frame):
    def __init__(self, prent, informacion="", subtotal=0):
        # begin wxGlade: ventana3.__init__
        super().__init__(prent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((1104, 590))
        self.SetTitle("frame_2")
        print(f"Datos de la ventana 2:\n Informacion: {informacion} \n")
        print(f"Subtotal: {subtotal}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(100, 153, 255))

        #variables de instancia ventana 3
        self.infoDulceria = ""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulces1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulces1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_5.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spComboB, 0, 0, 0)

        grid_sizer_11 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        grid_sizer_11.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas chicas\nRefresco chico\n")
        grid_sizer_11.Add(label_4, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitasG.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_3, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_5.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_12.Add(self.spComboC, 0, 0, 0)

        grid_sizer_13 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Amigos $130")
        grid_sizer_13.Add(label_2, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas medianas\n2 Refrescos medianos\n")
        grid_sizer_13.Add(label_5, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas2refrescos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_12.Add(bitmap_4, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        grid_sizer_14 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_6.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_14.Add(self.spComboF, 0, 0, 0)

        grid_sizer_2 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_14.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        grid_sizer_2.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G\n3 Refrescos G\n+1 Dulce")
        grid_sizer_2.Add(label_7, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_14.Add(bitmap_5, 0, 0, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_6, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        grid_sizer_4.Add(label_13, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spPalomitasCh, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        grid_sizer_15.Add(label_15, 0, 0, 0)

        grid_sizer_16 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_16.Add(self.spPalomitasMd, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        grid_sizer_16.Add(label_16, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasG, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        grid_sizer_17.Add(label_17, 0, 0, 0)

        grid_sizer_18 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_7, 0, 0, 0)

        grid_sizer_19 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_18.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        grid_sizer_19.Add(label_8, 0, 0, 0)

        grid_sizer_21 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_19.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        grid_sizer_21.Add(label_9, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_10.SetMinSize((31, 16))
        grid_sizer_21.Add(label_10, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        grid_sizer_21.Add(label_11, 0, 0, 0)

        grid_sizer_20 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_19.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_20.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_20.Add(self.cmbSabor, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_20.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar\n")
        grid_sizer_20.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        grid_sizer_22 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_8.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos agregados:")
        grid_sizer_22.Add(label_12, 0, 0, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        grid_sizer_22.Add(self.lbProductosAgregados, 0, 0, 0)

        grid_sizer_23 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_8.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        grid_sizer_23.Add(label_14, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubtotal.SetForegroundColour(wx.Colour(255, 42, 42))
        grid_sizer_23.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        grid_sizer_9.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        grid_sizer_9.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboAmigos)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregaRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboAmigos(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Amigos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*30
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas chicas \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasMd(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*45
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas medianas \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas grandes \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregaRefresco(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        if tamanyo == "CHICO":
            subtotalrefresco=numero*25
        elif tamanyo == "MEDIANO":
            subtotalrefresco=numero*40
        elif tamanyo == "GRANDE":
            subtotalrefresco=numero*60

        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero} Refresco: {sabor} tamaño {tamanyo} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)

        event.Skip()
    def limpiarD(self):
        #limpiamos las variables de instancia
        self.subtotalDulceria=0
        self.infoDulceria=""

        #limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("$00.00")
        self.lbSubtotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria. \n"
        f"¿Esta seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        f"Subtotal Dulceria: ${self.subtotalDulceria}",
        "Dulceria",style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()  #cerramos el dialogo

        if respuesta == wx.ID_YES:
            v4 = ventana4 (self, informacion=self.infoTaquilla, 
                            subtotal1=self.subtotalTaquilla,
                            informacion2=self.infoDulceria,
                            subtotal2=self.subtotalDulceria)
            v4.Show()
            self.Hide()

        elif respuesta == wx.ID_NO:
            self.limpiarD()
        
        
        event.Skip()

# end of class ventana3

class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((536, 409))
        self.SetTitle("frame_1")
        self.SetForegroundColour(wx.Colour(50, 153, 204))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(50, 153, 204))
        self.panel_1.SetForegroundColour(wx.Colour(50, 153, 204))
 
        #variables de instancia de la ventana2
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./boletos1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./boletos1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_2.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_3.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_4.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_3.Add(label_4, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Como entrenar a tu dragon", "Coraline", "Minecraft"], style=wx.CB_DROPDOWN)
        grid_sizer_4.Add(self.cmbPelicula, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSala.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_4.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario1.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./pelicula1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        label_6.SetForegroundColour(wx.Colour(0, 0, 0))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos(80):")
        label_8.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores(70):")
        label_9.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_7.Add(label_9, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_7.Add(self.tfMenores, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbSubtotal.SetForegroundColour(wx.Colour(0, 0, 0))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        grid_sizer_8.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        grid_sizer_8.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade
    def cargar_imagen(self,ruta):
        bitmap =wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)


    def seleccionPelicula(self, event):  # wxGlade: ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""

        print(f"Pelicula seleccionada: {pelicula}")
        if pelicula == "Como entrenar a tu dragon":
            imagen="pelicula1.png"
            sala="1"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"
        elif pelicula == "Coraline":
            imagen="pelicula2.png"
            sala="2"
            horario1="13:30"
            horario2="16:30"
            horario3="19:30"
        elif pelicula == "Minecraft":
            imagen="pelicula3.png"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"
        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabel()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabel()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabel()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido","Error", wx.OK | wx.ICON_ERROR)    
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido","Error", wx.OK | wx.ICON_ERROR)    
        event.Skip()
#creacion de la funcion limpiar para la ventana 2
    def limpiarValores_Campos(self):
        
        #limpiar variables de instancia 
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        #limpiar campos
        self.cargar_imagen("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.lbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")

    def limpiarTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n Adultos: {self.adultos}\n Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion} \n Subtotal: {self.subtotal}"

        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de Taquilla.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION    
        )
        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #cerramos el dialogo

        if respuesta == wx.ID_YES:
            print(f"Venta de Taquilla realizada\n {self.informacion}")
            v3 = ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()

        event.Skip()

# end of class ventana2

class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 333))
        self.SetTitle(u"Inicio de sesión - Cine Plus")
        self.SetForegroundColour(wx.Colour(39, 157, 39))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((900, 500))
        self.panel_1.SetBackgroundColour(wx.Colour(51, 207, 157))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, " bienvenidos a cine plus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(0, 0, 0))
        lbTitulo.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logo2.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario: ", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbUsuario.Wrap(100)
        sizer_1.Add(IbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 20))
        sizer_1.Add(lbClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()
        if nombre =="mariana"and clave == "1726":
            print(f"Bienvenida, {nombre}! Acceso autorizado.")
            v2 = ventana2(self)
            v2.Show()
            self.Hide()
        else:
            print("Acceso denegado. Usuario o clave incorrectos.")

        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cerrara la ventana.\n"\
                                    "¿Esta seguro que desea salir?","Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print("Bye!")
            self.Close()

        event.Skip()

# end of class ventana1

class MyApp(wx.App):
    def OnInit(self):
        self.inicio_de_sesion = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.inicio_de_sesion)
        self.inicio_de_sesion.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
